"""teste automatico

Revision ID: 66adbd3552aa
Revises: 
Create Date: 2023-10-05 22:19:15.119262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66adbd3552aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advogados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('oab', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeArquivo', sa.String(length=100), nullable=False),
    sa.Column('caminho', sa.String(length=255), nullable=False),
    sa.Column('extensao', sa.String(length=5), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processosJudiciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numeroProcesso', sa.String(length=12), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.Column('valorDaCausa', sa.DECIMAL(), nullable=True),
    sa.Column('advogado_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processosJudiciais')
    op.drop_table('documentos')
    op.drop_table('clientes')
    op.drop_table('advogados')
    # ### end Alembic commands ###
